
BODY:
 _d_SERVO_CHANNEL: 3
 _d_servo_angle: 0
 _led_on: true
 _backlight_color: #ffffff
 _emotion: happy

 
EYEBROWS:
 _l_angle: 90
 _r_angle: 90
 _l_SERVO_CHANNEL: 1
 _r_SERVO_CHANNEL: 0
 _led_on: True
 _led_color: #ffffff
 _emotion: happy


EYES:
 width: 128
 height: 128
 background_color: #ffffff
 eye_radius: 64
 eye_color: #ffffff
 pupil_radius: 25
 pupil_color: #1c86ee


HEAD:
 _h_angle: 90
 _v_angle: 90
 _emotion: happy
 _h_SERVO_CHANNEL: 3
 _v_SERVO_CHANNEL: 2
